### ISSUE TITLE
Why is `connect` a dependency

### ISSUE THREAD

**Issue by aadityataparia** [knpwrs/connect-static-transform#14]
Why is `connect` a dependency, when you can use this with express without installing connect? 

I see that it is using `connect` in examples, then maybe we can make it a `devDependency`?

**Comment by knpwrs** [comment]
This is one of my earliest public JavaScript projects and it hasn't been kept up to date. I think at one point it may have depended on `connect` explicitly but that dependency is no longer necessary. I'd be happy to accept a PR.
