### ISSUE TITLE
Make "match" optional

### ISSUE THREAD

**Issue by chucksellick** [knpwrs/connect-static-transform#4]
I did not expect the match option to be required - would expect the default behaviour to be to match all files and a regexp filter is only for more advanced scenarios (since I am checking file extensions in my handler anyway).

Additionally, omitting the match parameter produced an unexpected error, since the following code does not work as you expect:

  if (!(options.root || options.match || options.transform)) {
    throw new Error('options.{root,match,transform} must be defined');
  }

Instead I got this error:

 TypeError: Cannot read property 'test' of undefined
    at C:\Users\Pete\Documents\newsuk\test\node_modules\connect-static-transform\lib\staticTransform.js:59:23

**Comment by KenPowers** [comment]
I'll accept a pull request if you want to write it up.
